# Generated by Django 5.2.12 on 2026-03-20 14:52

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('current_version', models.CharField(blank=True, max_length=100)),
                ('expected_version', models.CharField(blank=True, max_length=100)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swim_compliance', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Device compliance records',
                'ordering': ['device'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoftwareImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('image_name', models.CharField(max_length=255)),
                ('image_file_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('image_type', models.CharField(default='software', max_length=20)),
                ('deployment_mode', models.CharField(default='universal', max_length=20)),
                ('min_source_version', models.CharField(blank=True, max_length=50)),
                ('max_source_version', models.CharField(blank=True, max_length=50)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('hash_md5', models.CharField(blank=True, max_length=32)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('hash_sha512', models.CharField(blank=True, max_length=128)),
                ('release_notes_url', models.URLField(blank=True)),
                ('min_ram_mb', models.IntegerField(blank=True, null=True)),
                ('min_flash_mb', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('device_types', models.ManyToManyField(blank=True, related_name='software_images', to='dcim.devicetype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_images', to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['platform', '-version'],
                'unique_together': {('platform', 'version', 'image_type')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UpgradeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_jobs', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_jobs', to='netbox_swim.softwareimage')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('order', models.PositiveIntegerField()),
                ('action_type', models.CharField(max_length=20)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('action_type', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(default='info', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='netbox_swim.upgradejob')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='netbox_swim.workflowstep')),
            ],
            options={
                'ordering': ['timestamp'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='netbox_swim.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='upgradejob',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='netbox_swim.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='GoldenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('deployment_mode', models.CharField(default='campus', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_images', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_designations', to='netbox_swim.softwareimage')),
            ],
            options={
                'ordering': ['device_type', 'deployment_mode'],
                'unique_together': {('device_type', 'deployment_mode')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('template', 'order')},
        ),
    ]
