# Generated by Django 5.2.12 on 2026-03-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('netbox_swim', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwareimage',
            unique_together={('platform', 'version', 'image_type', 'deployment_mode')},
        ),
    ]
