# Generated by Django 5.2.12 on 2026-03-20 15:06

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('netbox_swim', '0002_alter_softwareimage_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldenimage',
            options={'ordering': ['device_type', 'hardware_group']},
        ),
        migrations.AlterField(
            model_name='goldenimage',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='golden_images', to='dcim.devicetype'),
        ),
        migrations.CreateModel(
            name='HardwareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('min_version', models.CharField(blank=True, max_length=50)),
                ('max_version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('device_types', models.ManyToManyField(blank=True, related_name='hardware_groups', to='dcim.devicetype')),
                ('platforms', models.ManyToManyField(blank=True, related_name='hardware_groups', to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='goldenimage',
            unique_together={('device_type', 'deployment_mode')},
        ),
        migrations.AddField(
            model_name='goldenimage',
            name='hardware_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='golden_images', to='netbox_swim.hardwaregroup'),
        ),
        migrations.AddField(
            model_name='softwareimage',
            name='hardware_groups',
            field=models.ManyToManyField(blank=True, related_name='software_images', to='netbox_swim.hardwaregroup'),
        ),
        migrations.AlterUniqueTogether(
            name='goldenimage',
            unique_together={('device_type', 'deployment_mode'), ('hardware_group', 'deployment_mode')},
        ),
    ]
