# Generated by Django 5.2.12 on 2026-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_swim', '0003_alter_goldenimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaregroup',
            name='deployment_mode',
            field=models.CharField(default='universal', max_length=20),
        ),
    ]
