# Generated by Django 5.2.12 on 2026-03-20 15:50

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('netbox_swim', '0004_hardwaregroup_deployment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('base_path', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='swim_file_servers', to='dcim.device')),
                ('regions', models.ManyToManyField(blank=True, related_name='swim_file_servers', to='dcim.region')),
                ('sites', models.ManyToManyField(blank=True, related_name='swim_file_servers', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='softwareimage',
            name='file_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='netbox_swim.fileserver'),
        ),
    ]
