# Generated by Django 5.2.12 on 2026-03-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('netbox_swim', '0005_fileserver_softwareimage_file_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaregroup',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwaregroup',
            name='manual_excludes',
            field=models.ManyToManyField(blank=True, related_name='swim_excluded_groups', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='hardwaregroup',
            name='manual_includes',
            field=models.ManyToManyField(blank=True, related_name='swim_manual_groups', to='dcim.device'),
        ),
    ]
