# Generated by Django 5.2.12 on 2026-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_swim', '0006_hardwaregroup_is_static_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradejob',
            options={'ordering': ('-scheduled_time',)},
        ),
        migrations.AddField(
            model_name='upgradejob',
            name='job_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
