# Generated by Django 5.2.12 on 2026-03-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_swim', '0008_devicesyncrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesyncrecord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicesyncrecord',
            name='job_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
