# Generated by Django 5.2.12 on 2026-03-24 07:20

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_swim', '0009_devicesyncrecord_is_active_devicesyncrecord_job_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='upgradejob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='joblog',
            name='step',
        ),
        migrations.RemoveField(
            model_name='upgradejob',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='joblog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='result',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='upgradejob',
            name='target_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_swim.softwareimage'),
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=30)),
                ('connection_library', models.CharField(default='scrapli', max_length=50)),
                ('max_concurrency', models.PositiveIntegerField(default=5)),
                ('selected_device_count', models.PositiveIntegerField(default=0)),
                ('failed_device_count', models.PositiveIntegerField(default=0)),
                ('summary_logs', models.JSONField(blank=True, default=list, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-start_time',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='devicesyncrecord',
            name='sync_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_records', to='netbox_swim.syncjob'),
        ),
    ]
