# Generated by Django 5.2.12 on 2026-03-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_swim', '0010_alter_joblog_options_alter_upgradejob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesyncrecord',
            name='live_facts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='hardwaregroup',
            name='connection_priority',
            field=models.CharField(default='scrapli,netmiko,unicon', max_length=100),
        ),
        migrations.AddField(
            model_name='hardwaregroup',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_groups', to='netbox_swim.workflowtemplate'),
        ),
    ]
